--- Day 3: Lobby ---
You descend a short staircase, enter the surprisingly vast lobby, and are quickly cleared by the security checkpoint. When you get to the main elevators, however, you discover that each one has a red light above it: they're all offline.

"Sorry about that," an Elf apologizes as she tinkers with a nearby control panel. "Some kind of electrical surge seems to have fried them. I'll try to get them online soon."

You explain your need to get further underground. "Well, you could at least take the escalator down to the printing department, not that you'd get much further than that without the elevators working. That is, you could if the escalator weren't also offline."

"But, don't worry! It's not fried; it just needs power. Maybe you can get it running while I keep working on the elevators."

There are batteries nearby that can supply emergency power to the escalator for just such an occasion. The batteries are each labeled with their joltage rating, a value from 1 to 9. You make a note of their joltage ratings (your puzzle input). For example:

987654321111111
811111111111119
234234234234278
818181911112111
The batteries are arranged into banks; each line of digits in your input corresponds to a single bank of batteries. Within each bank, you need to turn on exactly two batteries; the joltage that the bank produces is equal to the number formed by the digits on the batteries you've turned on. For example, if you have a bank like 12345 and you turn on batteries 2 and 4, the bank would produce 24 jolts. (You cannot rearrange batteries.)

You'll need to find the largest possible joltage each bank can produce. In the above example:

In 987654321111111, you can make the largest joltage possible, 98, by turning on the first two batteries.
In 811111111111119, you can make the largest joltage possible by turning on the batteries labeled 8 and 9, producing 89 jolts.
In 234234234234278, you can make 78 by turning on the last two batteries (marked 7 and 8).
In 818181911112111, the largest joltage you can produce is 92.
The total output joltage is the sum of the maximum joltage from each bank, so in this example, the total output joltage is 98 + 89 + 78 + 92 = 357.

There are many batteries in front of you. Find the maximum joltage possible from each bank; what is the total output joltage?

In [ ]:
from aocd import get_data, submit

In [ ]:
data = get_data(year = 2025, day = 3)
data_ls = data.splitlines()
data_ls[:5]

['2221222621311222213132242151213242132162234231144212112222231222222222122221122241223232322424322112',
 '3543326422247421243461523246251225253652324623123514155262436222322736212622632535261512337153224225',
 '3222222314222211221232222212222122123212133222228331212211323332221223322223222121221222222212212121',
 '3224323622236944523235623633582354553243243425462556164564534655532214442234136726342452535235224521',
 '4463242484324251544436315213253238423242742225441254332255425532344624856246285453554421653275554443']

In [ ]:
example_ls = """987654321111111
811111111111119
234234234234278
818181911112111""".splitlines()
example_ls

['987654321111111', '811111111111119', '234234234234278', '818181911112111']

In [ ]:
bank = example_ls[0]

In [ ]:
bank[0:]

'987654321111111'

In [ ]:
max_joltage = 0
for ix1, joltage1 in enumerate(bank):
    for joltage2 in bank[(ix1+1):]:
        total_joltage = joltage1 + joltage2
        max_joltage = max(int(total_joltage), max_joltage)

In [ ]:
max_joltage

98

In [ ]:
def pt1(data_ls):
    total = 0
    for bank in data_ls:
        max_joltage = 0
        for ix1, joltage1 in enumerate(bank):
            for joltage2 in bank[(ix1+1):]:
                total_joltage = joltage1 + joltage2
                max_joltage = max(int(total_joltage), max_joltage)
        
        total += max_joltage
    
    return total

In [ ]:
pt1(example_ls)

357

In [ ]:
pt1_answer = pt1(data_ls)
pt1_answer

17100

In [ ]:
submit(pt1_answer, part = "a", year = 2025, day = 3)

That's the right answer!  You are one gold star closer to decorating the North Pole. [Continue to Part Two]


either that was super easy or I'm getting better at these.

--- Part Two ---
The escalator doesn't move. The Elf explains that it probably needs more joltage to overcome the static friction of the system and hits the big red "joltage limit safety override" button. You lose count of the number of times she needs to confirm "yes, I'm sure" and decorate the lobby a bit while you wait.

Now, you need to make the largest joltage by turning on exactly twelve batteries within each bank.

The joltage output for the bank is still the number formed by the digits of the batteries you've turned on; the only difference is that now there will be 12 digits in each bank's joltage output instead of two.

Consider again the example from before:

987654321111111
811111111111119
234234234234278
818181911112111
Now, the joltages are much larger:

In 987654321111111, the largest joltage can be found by turning on everything except some 1s at the end to produce 987654321111.
In the digit sequence 811111111111119, the largest joltage can be found by turning on everything except some 1s, producing 811111111119.
In 234234234234278, the largest joltage can be found by turning on everything except a 2 battery, a 3 battery, and another 2 battery near the start to produce 434234234278.
In 818181911112111, the joltage 888911112111 is produced by turning on everything except some 1s near the front.
The total output joltage is now much larger: 987654321111 + 811111111119 + 434234234278 + 888911112111 = 3121910778619.

What is the new total output joltage?

Hmm. Okay trying to work out how to address this. 

I could adjust the loop to run 12 iterations, incrementing the index every time. can you show the best way to do that programatically?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Sure! For selecting 12 batteries, you'll want to use nested loops or a more elegant approach. Here's a clean way using `itertools.combinations`:

```python
from itertools import combinations

bank = example_ls[0]
max_joltage = 0

for indices in combinations(range(len(bank)), 12):
    joltage = int(''.join(bank[i] for i in indices))
    max_joltage = max(joltage, max_joltage)

print(max_joltage)
```

This generates all possible ways to choose 12 positions from the bank, then constructs the number from those digits.

Does this approach make sense? Try it on the first example bank to see if it gives you `987654321111`.

In [ ]:
from itertools import combinations

bank = example_ls[0]
max_joltage = 0

for indices in combinations(range(len(bank)), 12):
    joltage = int(''.join(bank[i] for i in indices))
    max_joltage = max(joltage, max_joltage)

print(max_joltage)

987654321111


In [ ]:
def pt2(data_ls):
    total = 0
    for bank in data_ls:
        max_joltage = 0
        for indices in combinations(range(len(bank)), 12):
            joltage = int(''.join(bank[i] for i in indices))
            max_joltage = max(joltage, max_joltage)
        
        total += max_joltage
    
    return total

In [ ]:
pt2(example_ls)

3121910778619

In [ ]:
len(data_ls)

200

is there a way I can run this function within a timeout context, so that it will stop if its taking a certain amount of time to run?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Yes! You can use the `signal` module to set a timeout. Here's a simple approach:

```python
import signal

def timeout_handler(signum, frame):
    raise TimeoutError("Function took too long")

signal.signal(signal.SIGALRM, timeout_handler)
signal.alarm(10)  # 10 second timeout

try:
    result = pt2(data_ls)
    signal.alarm(0)  # Cancel the alarm
    print(result)
except TimeoutError as e:
    print(f"Timeout: {e}")
```

This will stop execution after 10 seconds. You can adjust the timeout value as needed.

Want to try this and see if your current solution completes in a reasonable time?

In [ ]:
import signal

def timeout_handler(signum, frame):
    raise TimeoutError("Function took too long")

signal.signal(signal.SIGALRM, timeout_handler)
signal.alarm(20)  # 20 second timeout

try:
    result = pt2([data_ls[0]])
    signal.alarm(0)  # Cancel the alarm
    print(result)
except TimeoutError as e:
    print(f"Timeout: {e}")

Timeout: Function took too long


it seems to work on the examples, but will take too long to run on the full data. I think this approach doesn't scale well to large banks, as combinations will explode in size. 

What could be an alternative approach, I guess that only partially iterates rather than looking at all combinations

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Good observation! With a 100-digit bank, choosing 12 positions gives you about 10^17 combinations - way too many.

Here's the key insight: to maximize the number, you want the **largest digits in the leftmost positions**. So instead of trying all combinations, you could use a **greedy approach**:

1. Start from the left
2. At each position, pick the largest available digit that still leaves enough digits to reach 12 total

For example, in `987654321111111`:
- Pick the `9` (1st digit, 11 more needed, 14 digits remain ✓)
- Pick the `8` (2nd digit, 10 more needed, 13 digits remain ✓)
- Continue...

Would you like to try implementing this greedy strategy, or would you like me to show you a code sketch of how it might work?

yeah sketch out how this could work

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Here's a sketch of the greedy approach:

```python
def max_joltage_greedy(bank, num_batteries=12):
    result = []
    start = 0
    
    for pos in range(num_batteries):
        remaining = num_batteries - pos  # How many more digits we need
        # We can look ahead up to: len(bank) - start - remaining + 1
        search_end = len(bank) - remaining + 1
        
        # Find the largest digit in our search window
        best_digit = max(bank[start:search_end])
        best_index = bank.index(best_digit, start)
        
        result.append(best_digit)
        start = best_index + 1  # Next search starts after this digit
    
    return int(''.join(result))
```

The key idea: at each step, you search a window that ensures you'll have enough digits left to complete your selection.

Try implementing this and test it on `example_ls[0]` - does it give you `987654321111`?

In [ ]:
def max_joltage_greedy(bank, num_batteries=12):
    result = []
    start = 0
    
    for pos in range(num_batteries):
        remaining = num_batteries - pos  # How many more digits we need
        # We can look ahead up to: len(bank) - start - remaining + 1
        search_end = len(bank) - remaining + 1
        
        # Find the largest digit in our search window
        best_digit = max(bank[start:search_end])
        best_index = bank.index(best_digit, start)
        
        result.append(best_digit)
        start = best_index + 1  # Next search starts after this digit
    
    return int(''.join(result))

def pt2(data_ls):
    total = 0

    for bank in data_ls:
        total += max_joltage_greedy(bank)
    
    return total

In [ ]:
pt2(example_ls)

3121910778619

In [ ]:
%time pt2_answer = pt2(data_ls)

CPU times: user 2.2 ms, sys: 0 ns, total: 2.2 ms
Wall time: 2.2 ms


In [ ]:
pt2_answer

170418192256861

In [ ]:
submit(pt2_answer, part = "b", year = 2025, day = 3)

That's the right answer!  You are one gold star closer to decorating the North Pole.You have completed Day 3! You can [Shareon
  Bluesky
Twitter
Mastodon] this victory or [Return to Your Advent Calendar].
